name: Package Electron Manual
on: workflow_dispatch
jobs:
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm install
          npm run elrebuild
          node build.js
          npm run buildcss
          npx electron-packager . --out dist --ignore .gitignore --ignore /src/frontend --ignore /src/backend
      - run: |
          cd dist
          zip -r hyacinth-linux-x64.zip hyacinth-linux-x64
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-app-linux
          path: dist/hyacinth-linux-x64.zip
  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm install
          npm run elrebuild
          node build.js
          npm run buildcss
          npx electron-packager . --out dist --ignore .gitignore --ignore /src/frontend --ignore /src/backend
      - run: |
          cd dist/hyacinth-darwin-x64
          zip -r hyacinth.app.zip hyacinth.app
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-app-macos
          path: dist/hyacinth-darwin-x64/hyacinth.app.zip
  package-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm install
          npm run elrebuild
          node build.js
          npm run buildcss
          npx electron-packager . --out dist --ignore .gitignore --ignore /src/frontend --ignore /src/backend
      - run: |
          cd dist
          Compress-Archive -Path hyacinth-win32-x64 -DestinationPath hyacinth-win32-x64.zip
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-app-win32
          path: dist/hyacinth-win32-x64.zip
