name: Package Electron Manual
on: workflow_dispatch
jobs:
  package-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: ls
      - run: |
          npm install
          npm run elrebuild
          npm run buildjsfront
          npm run buildjsback
          npm run buildcss
          npx electron-packager . --out dist --ignore .gitignore --ignore "/src/(frontend|backend)"
      - run: ls dist/hyacinth-darwin-x64
      - run: ls dist/hyacinth-darwin-x64/hyacinth.app
